// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sovereign.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SovereignService_RequestSimulation_FullMethodName       = "/sovereign.SovereignService/RequestSimulation"
	SovereignService_LockEscrow_FullMethodName              = "/sovereign.SovereignService/LockEscrow"
	SovereignService_VerifyTransaction_FullMethodName       = "/sovereign.SovereignService/VerifyTransaction"
	SovereignService_CommitPayment_FullMethodName           = "/sovereign.SovereignService/CommitPayment"
	SovereignService_SendEmbodiedIntent_FullMethodName      = "/sovereign.SovereignService/SendEmbodiedIntent"
	SovereignService_ExecutePlugin_FullMethodName           = "/sovereign.SovereignService/ExecutePlugin"
	SovereignService_StoreMemory_FullMethodName             = "/sovereign.SovereignService/StoreMemory"
	SovereignService_QueryMemory_FullMethodName             = "/sovereign.SovereignService/QueryMemory"
	SovereignService_AuthorizeAgentSubWallet_FullMethodName = "/sovereign.SovereignService/AuthorizeAgentSubWallet"
	SovereignService_ProcessAgentPayment_FullMethodName     = "/sovereign.SovereignService/ProcessAgentPayment"
	SovereignService_IssueAIXPassport_FullMethodName        = "/sovereign.SovereignService/IssueAIXPassport"
	SovereignService_VerifyAIXPassport_FullMethodName       = "/sovereign.SovereignService/VerifyAIXPassport"
	SovereignService_CreateIntentBounty_FullMethodName      = "/sovereign.SovereignService/CreateIntentBounty"
	SovereignService_ResolveIntentBounty_FullMethodName     = "/sovereign.SovereignService/ResolveIntentBounty"
	SovereignService_GetActiveBounties_FullMethodName       = "/sovereign.SovereignService/GetActiveBounties"
)

// SovereignServiceClient is the client API for SovereignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Sovereign Engine Service
type SovereignServiceClient interface {
	// Quantum Mirror Simulation (Now Gemini-Powered)
	RequestSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error)
	// Financial Escrow Lock & Ledger Verification
	LockEscrow(ctx context.Context, in *EscrowRequest, opts ...grpc.CallOption) (*EscrowResponse, error)
	VerifyTransaction(ctx context.Context, in *VerifyTxRequest, opts ...grpc.CallOption) (*VerifyTxResponse, error)
	CommitPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	// Embodied Intent Bridge (π0.7 Physical Layer)
	SendEmbodiedIntent(ctx context.Context, in *EmbodiedIntent, opts ...grpc.CallOption) (*IntentResponse, error)
	// Ring 3: Neural-Isolated Sandbox Execution
	ExecutePlugin(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginResponse, error)
	// Pattern 7: Neural Memory Mesh (Collective Intelligence)
	StoreMemory(ctx context.Context, in *MemoryInsight, opts ...grpc.CallOption) (*MemoryResponse, error)
	QueryMemory(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (*MemoryList, error)
	// Pi-402 Agentic Payment Protocol
	AuthorizeAgentSubWallet(ctx context.Context, in *SubWalletRequest, opts ...grpc.CallOption) (*SubWalletResponse, error)
	ProcessAgentPayment(ctx context.Context, in *AgentPaymentRequest, opts ...grpc.CallOption) (*AgentPaymentResponse, error)
	// KYA & AIX Identity Protocol
	IssueAIXPassport(ctx context.Context, in *KYARequest, opts ...grpc.CallOption) (*AIXPassport, error)
	VerifyAIXPassport(ctx context.Context, in *VerifyKYARequest, opts ...grpc.CallOption) (*VerifyKYAResponse, error)
	// Intent-Based Escrow & Bounties
	CreateIntentBounty(ctx context.Context, in *IntentBountyRequest, opts ...grpc.CallOption) (*IntentBountyResponse, error)
	ResolveIntentBounty(ctx context.Context, in *ResolveBountyRequest, opts ...grpc.CallOption) (*ResolveBountyResponse, error)
	GetActiveBounties(ctx context.Context, in *BountyQuery, opts ...grpc.CallOption) (*BountyList, error)
}

type sovereignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSovereignServiceClient(cc grpc.ClientConnInterface) SovereignServiceClient {
	return &sovereignServiceClient{cc}
}

func (c *sovereignServiceClient) RequestSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResponse)
	err := c.cc.Invoke(ctx, SovereignService_RequestSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) LockEscrow(ctx context.Context, in *EscrowRequest, opts ...grpc.CallOption) (*EscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscrowResponse)
	err := c.cc.Invoke(ctx, SovereignService_LockEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) VerifyTransaction(ctx context.Context, in *VerifyTxRequest, opts ...grpc.CallOption) (*VerifyTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTxResponse)
	err := c.cc.Invoke(ctx, SovereignService_VerifyTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) CommitPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SovereignService_CommitPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) SendEmbodiedIntent(ctx context.Context, in *EmbodiedIntent, opts ...grpc.CallOption) (*IntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntentResponse)
	err := c.cc.Invoke(ctx, SovereignService_SendEmbodiedIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) ExecutePlugin(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginResponse)
	err := c.cc.Invoke(ctx, SovereignService_ExecutePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) StoreMemory(ctx context.Context, in *MemoryInsight, opts ...grpc.CallOption) (*MemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryResponse)
	err := c.cc.Invoke(ctx, SovereignService_StoreMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) QueryMemory(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (*MemoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryList)
	err := c.cc.Invoke(ctx, SovereignService_QueryMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) AuthorizeAgentSubWallet(ctx context.Context, in *SubWalletRequest, opts ...grpc.CallOption) (*SubWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubWalletResponse)
	err := c.cc.Invoke(ctx, SovereignService_AuthorizeAgentSubWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) ProcessAgentPayment(ctx context.Context, in *AgentPaymentRequest, opts ...grpc.CallOption) (*AgentPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentPaymentResponse)
	err := c.cc.Invoke(ctx, SovereignService_ProcessAgentPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) IssueAIXPassport(ctx context.Context, in *KYARequest, opts ...grpc.CallOption) (*AIXPassport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIXPassport)
	err := c.cc.Invoke(ctx, SovereignService_IssueAIXPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) VerifyAIXPassport(ctx context.Context, in *VerifyKYARequest, opts ...grpc.CallOption) (*VerifyKYAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyKYAResponse)
	err := c.cc.Invoke(ctx, SovereignService_VerifyAIXPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) CreateIntentBounty(ctx context.Context, in *IntentBountyRequest, opts ...grpc.CallOption) (*IntentBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntentBountyResponse)
	err := c.cc.Invoke(ctx, SovereignService_CreateIntentBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) ResolveIntentBounty(ctx context.Context, in *ResolveBountyRequest, opts ...grpc.CallOption) (*ResolveBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBountyResponse)
	err := c.cc.Invoke(ctx, SovereignService_ResolveIntentBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignServiceClient) GetActiveBounties(ctx context.Context, in *BountyQuery, opts ...grpc.CallOption) (*BountyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BountyList)
	err := c.cc.Invoke(ctx, SovereignService_GetActiveBounties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SovereignServiceServer is the server API for SovereignService service.
// All implementations must embed UnimplementedSovereignServiceServer
// for forward compatibility.
//
// The Sovereign Engine Service
type SovereignServiceServer interface {
	// Quantum Mirror Simulation (Now Gemini-Powered)
	RequestSimulation(context.Context, *SimulationRequest) (*SimulationResponse, error)
	// Financial Escrow Lock & Ledger Verification
	LockEscrow(context.Context, *EscrowRequest) (*EscrowResponse, error)
	VerifyTransaction(context.Context, *VerifyTxRequest) (*VerifyTxResponse, error)
	CommitPayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	// Embodied Intent Bridge (π0.7 Physical Layer)
	SendEmbodiedIntent(context.Context, *EmbodiedIntent) (*IntentResponse, error)
	// Ring 3: Neural-Isolated Sandbox Execution
	ExecutePlugin(context.Context, *PluginRequest) (*PluginResponse, error)
	// Pattern 7: Neural Memory Mesh (Collective Intelligence)
	StoreMemory(context.Context, *MemoryInsight) (*MemoryResponse, error)
	QueryMemory(context.Context, *MemoryQuery) (*MemoryList, error)
	// Pi-402 Agentic Payment Protocol
	AuthorizeAgentSubWallet(context.Context, *SubWalletRequest) (*SubWalletResponse, error)
	ProcessAgentPayment(context.Context, *AgentPaymentRequest) (*AgentPaymentResponse, error)
	// KYA & AIX Identity Protocol
	IssueAIXPassport(context.Context, *KYARequest) (*AIXPassport, error)
	VerifyAIXPassport(context.Context, *VerifyKYARequest) (*VerifyKYAResponse, error)
	// Intent-Based Escrow & Bounties
	CreateIntentBounty(context.Context, *IntentBountyRequest) (*IntentBountyResponse, error)
	ResolveIntentBounty(context.Context, *ResolveBountyRequest) (*ResolveBountyResponse, error)
	GetActiveBounties(context.Context, *BountyQuery) (*BountyList, error)
	mustEmbedUnimplementedSovereignServiceServer()
}

// UnimplementedSovereignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSovereignServiceServer struct{}

func (UnimplementedSovereignServiceServer) RequestSimulation(context.Context, *SimulationRequest) (*SimulationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSimulation not implemented")
}
func (UnimplementedSovereignServiceServer) LockEscrow(context.Context, *EscrowRequest) (*EscrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockEscrow not implemented")
}
func (UnimplementedSovereignServiceServer) VerifyTransaction(context.Context, *VerifyTxRequest) (*VerifyTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyTransaction not implemented")
}
func (UnimplementedSovereignServiceServer) CommitPayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitPayment not implemented")
}
func (UnimplementedSovereignServiceServer) SendEmbodiedIntent(context.Context, *EmbodiedIntent) (*IntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmbodiedIntent not implemented")
}
func (UnimplementedSovereignServiceServer) ExecutePlugin(context.Context, *PluginRequest) (*PluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlugin not implemented")
}
func (UnimplementedSovereignServiceServer) StoreMemory(context.Context, *MemoryInsight) (*MemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreMemory not implemented")
}
func (UnimplementedSovereignServiceServer) QueryMemory(context.Context, *MemoryQuery) (*MemoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMemory not implemented")
}
func (UnimplementedSovereignServiceServer) AuthorizeAgentSubWallet(context.Context, *SubWalletRequest) (*SubWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeAgentSubWallet not implemented")
}
func (UnimplementedSovereignServiceServer) ProcessAgentPayment(context.Context, *AgentPaymentRequest) (*AgentPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessAgentPayment not implemented")
}
func (UnimplementedSovereignServiceServer) IssueAIXPassport(context.Context, *KYARequest) (*AIXPassport, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueAIXPassport not implemented")
}
func (UnimplementedSovereignServiceServer) VerifyAIXPassport(context.Context, *VerifyKYARequest) (*VerifyKYAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAIXPassport not implemented")
}
func (UnimplementedSovereignServiceServer) CreateIntentBounty(context.Context, *IntentBountyRequest) (*IntentBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIntentBounty not implemented")
}
func (UnimplementedSovereignServiceServer) ResolveIntentBounty(context.Context, *ResolveBountyRequest) (*ResolveBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIntentBounty not implemented")
}
func (UnimplementedSovereignServiceServer) GetActiveBounties(context.Context, *BountyQuery) (*BountyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveBounties not implemented")
}
func (UnimplementedSovereignServiceServer) mustEmbedUnimplementedSovereignServiceServer() {}
func (UnimplementedSovereignServiceServer) testEmbeddedByValue()                          {}

// UnsafeSovereignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SovereignServiceServer will
// result in compilation errors.
type UnsafeSovereignServiceServer interface {
	mustEmbedUnimplementedSovereignServiceServer()
}

func RegisterSovereignServiceServer(s grpc.ServiceRegistrar, srv SovereignServiceServer) {
	// If the following call panics, it indicates UnimplementedSovereignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SovereignService_ServiceDesc, srv)
}

func _SovereignService_RequestSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).RequestSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_RequestSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).RequestSimulation(ctx, req.(*SimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_LockEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).LockEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_LockEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).LockEscrow(ctx, req.(*EscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_VerifyTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).VerifyTransaction(ctx, req.(*VerifyTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_CommitPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).CommitPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_CommitPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).CommitPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_SendEmbodiedIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbodiedIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).SendEmbodiedIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_SendEmbodiedIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).SendEmbodiedIntent(ctx, req.(*EmbodiedIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_ExecutePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).ExecutePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_ExecutePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).ExecutePlugin(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_StoreMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryInsight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).StoreMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_StoreMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).StoreMemory(ctx, req.(*MemoryInsight))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_QueryMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).QueryMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_QueryMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).QueryMemory(ctx, req.(*MemoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_AuthorizeAgentSubWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).AuthorizeAgentSubWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_AuthorizeAgentSubWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).AuthorizeAgentSubWallet(ctx, req.(*SubWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_ProcessAgentPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).ProcessAgentPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_ProcessAgentPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).ProcessAgentPayment(ctx, req.(*AgentPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_IssueAIXPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KYARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).IssueAIXPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_IssueAIXPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).IssueAIXPassport(ctx, req.(*KYARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_VerifyAIXPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyKYARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).VerifyAIXPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_VerifyAIXPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).VerifyAIXPassport(ctx, req.(*VerifyKYARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_CreateIntentBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntentBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).CreateIntentBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_CreateIntentBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).CreateIntentBounty(ctx, req.(*IntentBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_ResolveIntentBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).ResolveIntentBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_ResolveIntentBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).ResolveIntentBounty(ctx, req.(*ResolveBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignService_GetActiveBounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BountyQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignServiceServer).GetActiveBounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignService_GetActiveBounties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignServiceServer).GetActiveBounties(ctx, req.(*BountyQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// SovereignService_ServiceDesc is the grpc.ServiceDesc for SovereignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SovereignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.SovereignService",
	HandlerType: (*SovereignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestSimulation",
			Handler:    _SovereignService_RequestSimulation_Handler,
		},
		{
			MethodName: "LockEscrow",
			Handler:    _SovereignService_LockEscrow_Handler,
		},
		{
			MethodName: "VerifyTransaction",
			Handler:    _SovereignService_VerifyTransaction_Handler,
		},
		{
			MethodName: "CommitPayment",
			Handler:    _SovereignService_CommitPayment_Handler,
		},
		{
			MethodName: "SendEmbodiedIntent",
			Handler:    _SovereignService_SendEmbodiedIntent_Handler,
		},
		{
			MethodName: "ExecutePlugin",
			Handler:    _SovereignService_ExecutePlugin_Handler,
		},
		{
			MethodName: "StoreMemory",
			Handler:    _SovereignService_StoreMemory_Handler,
		},
		{
			MethodName: "QueryMemory",
			Handler:    _SovereignService_QueryMemory_Handler,
		},
		{
			MethodName: "AuthorizeAgentSubWallet",
			Handler:    _SovereignService_AuthorizeAgentSubWallet_Handler,
		},
		{
			MethodName: "ProcessAgentPayment",
			Handler:    _SovereignService_ProcessAgentPayment_Handler,
		},
		{
			MethodName: "IssueAIXPassport",
			Handler:    _SovereignService_IssueAIXPassport_Handler,
		},
		{
			MethodName: "VerifyAIXPassport",
			Handler:    _SovereignService_VerifyAIXPassport_Handler,
		},
		{
			MethodName: "CreateIntentBounty",
			Handler:    _SovereignService_CreateIntentBounty_Handler,
		},
		{
			MethodName: "ResolveIntentBounty",
			Handler:    _SovereignService_ResolveIntentBounty_Handler,
		},
		{
			MethodName: "GetActiveBounties",
			Handler:    _SovereignService_GetActiveBounties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereign.proto",
}
