// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sovereign.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Instances     int32                  `protobuf:"varint,2,opt,name=instances,proto3" json:"instances,omitempty"`
	Complexity    float32                `protobuf:"fixed32,3,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Personas      []string               `protobuf:"bytes,4,rep,name=personas,proto3" json:"personas,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // e.g. "gemini-1.5-pro"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRequest) Reset() {
	*x = SimulationRequest{}
	mi := &file_sovereign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRequest) ProtoMessage() {}

func (x *SimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRequest.ProtoReflect.Descriptor instead.
func (*SimulationRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *SimulationRequest) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *SimulationRequest) GetComplexity() float32 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

func (x *SimulationRequest) GetPersonas() []string {
	if x != nil {
		return x.Personas
	}
	return nil
}

func (x *SimulationRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type SimulationResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GoalId                 string                 `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	PredictedRoi           float32                `protobuf:"fixed32,2,opt,name=predicted_roi,json=predictedRoi,proto3" json:"predicted_roi,omitempty"`
	RiskScore              float32                `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	StrategyRecommendation string                 `protobuf:"bytes,4,opt,name=strategy_recommendation,json=strategyRecommendation,proto3" json:"strategy_recommendation,omitempty"`
	Reasoning              *GeminiReasoning       `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	EstimatedRevenueUsd    float32                `protobuf:"fixed32,6,opt,name=estimated_revenue_usd,json=estimatedRevenueUsd,proto3" json:"estimated_revenue_usd,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SimulationResponse) Reset() {
	*x = SimulationResponse{}
	mi := &file_sovereign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResponse) ProtoMessage() {}

func (x *SimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResponse.ProtoReflect.Descriptor instead.
func (*SimulationResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationResponse) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *SimulationResponse) GetPredictedRoi() float32 {
	if x != nil {
		return x.PredictedRoi
	}
	return 0
}

func (x *SimulationResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SimulationResponse) GetStrategyRecommendation() string {
	if x != nil {
		return x.StrategyRecommendation
	}
	return ""
}

func (x *SimulationResponse) GetReasoning() *GeminiReasoning {
	if x != nil {
		return x.Reasoning
	}
	return nil
}

func (x *SimulationResponse) GetEstimatedRevenueUsd() float32 {
	if x != nil {
		return x.EstimatedRevenueUsd
	}
	return 0
}

type GeminiReasoning struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogicChain      string                 `protobuf:"bytes,1,opt,name=logic_chain,json=logicChain,proto3" json:"logic_chain,omitempty"`
	CriticalRisks   []string               `protobuf:"bytes,2,rep,name=critical_risks,json=criticalRisks,proto3" json:"critical_risks,omitempty"`
	Opportunities   []string               `protobuf:"bytes,3,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	ConfidenceScore string                 `protobuf:"bytes,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeminiReasoning) Reset() {
	*x = GeminiReasoning{}
	mi := &file_sovereign_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiReasoning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiReasoning) ProtoMessage() {}

func (x *GeminiReasoning) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiReasoning.ProtoReflect.Descriptor instead.
func (*GeminiReasoning) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{2}
}

func (x *GeminiReasoning) GetLogicChain() string {
	if x != nil {
		return x.LogicChain
	}
	return ""
}

func (x *GeminiReasoning) GetCriticalRisks() []string {
	if x != nil {
		return x.CriticalRisks
	}
	return nil
}

func (x *GeminiReasoning) GetOpportunities() []string {
	if x != nil {
		return x.Opportunities
	}
	return nil
}

func (x *GeminiReasoning) GetConfidenceScore() string {
	if x != nil {
		return x.ConfidenceScore
	}
	return ""
}

type EmbodiedIntent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IntentId          string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SubtaskLanguage   string                 `protobuf:"bytes,3,opt,name=subtask_language,json=subtaskLanguage,proto3" json:"subtask_language,omitempty"`
	ExecutionMetadata map[string]string      `protobuf:"bytes,4,rep,name=execution_metadata,json=executionMetadata,proto3" json:"execution_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ControlMode       string                 `protobuf:"bytes,5,opt,name=control_mode,json=controlMode,proto3" json:"control_mode,omitempty"`
	VisualSubgoals    [][]byte               `protobuf:"bytes,6,rep,name=visual_subgoals,json=visualSubgoals,proto3" json:"visual_subgoals,omitempty"`
	// goal and persona are passed to the hybrid reasoning layer in
	// SendEmbodiedIntent (sidecar/sovereign-engine/pkg/server/server.go).
	Goal          string `protobuf:"bytes,7,opt,name=goal,proto3" json:"goal,omitempty"`
	Persona       string `protobuf:"bytes,8,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbodiedIntent) Reset() {
	*x = EmbodiedIntent{}
	mi := &file_sovereign_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbodiedIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbodiedIntent) ProtoMessage() {}

func (x *EmbodiedIntent) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbodiedIntent.ProtoReflect.Descriptor instead.
func (*EmbodiedIntent) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{3}
}

func (x *EmbodiedIntent) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *EmbodiedIntent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EmbodiedIntent) GetSubtaskLanguage() string {
	if x != nil {
		return x.SubtaskLanguage
	}
	return ""
}

func (x *EmbodiedIntent) GetExecutionMetadata() map[string]string {
	if x != nil {
		return x.ExecutionMetadata
	}
	return nil
}

func (x *EmbodiedIntent) GetControlMode() string {
	if x != nil {
		return x.ControlMode
	}
	return ""
}

func (x *EmbodiedIntent) GetVisualSubgoals() [][]byte {
	if x != nil {
		return x.VisualSubgoals
	}
	return nil
}

func (x *EmbodiedIntent) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *EmbodiedIntent) GetPersona() string {
	if x != nil {
		return x.Persona
	}
	return ""
}

type IntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	TrackingId    string                 `protobuf:"bytes,3,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentResponse) Reset() {
	*x = IntentResponse{}
	mi := &file_sovereign_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentResponse) ProtoMessage() {}

func (x *IntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentResponse.ProtoReflect.Descriptor instead.
func (*IntentResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{4}
}

func (x *IntentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IntentResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *IntentResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type EscrowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	AmountPi      float64                `protobuf:"fixed64,2,opt,name=amount_pi,json=amountPi,proto3" json:"amount_pi,omitempty"`
	TargetWallet  string                 `protobuf:"bytes,3,opt,name=target_wallet,json=targetWallet,proto3" json:"target_wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowRequest) Reset() {
	*x = EscrowRequest{}
	mi := &file_sovereign_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowRequest) ProtoMessage() {}

func (x *EscrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowRequest.ProtoReflect.Descriptor instead.
func (*EscrowRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{5}
}

func (x *EscrowRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *EscrowRequest) GetAmountPi() float64 {
	if x != nil {
		return x.AmountPi
	}
	return 0
}

func (x *EscrowRequest) GetTargetWallet() string {
	if x != nil {
		return x.TargetWallet
	}
	return ""
}

type EscrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	EscrowAddress string                 `protobuf:"bytes,2,opt,name=escrow_address,json=escrowAddress,proto3" json:"escrow_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowResponse) Reset() {
	*x = EscrowResponse{}
	mi := &file_sovereign_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowResponse) ProtoMessage() {}

func (x *EscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowResponse.ProtoReflect.Descriptor instead.
func (*EscrowResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{6}
}

func (x *EscrowResponse) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *EscrowResponse) GetEscrowAddress() string {
	if x != nil {
		return x.EscrowAddress
	}
	return ""
}

type VerifyTxRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TxId             string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ExpectedReceiver string                 `protobuf:"bytes,2,opt,name=expected_receiver,json=expectedReceiver,proto3" json:"expected_receiver,omitempty"`
	ExpectedAmount   float64                `protobuf:"fixed64,3,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyTxRequest) Reset() {
	*x = VerifyTxRequest{}
	mi := &file_sovereign_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxRequest) ProtoMessage() {}

func (x *VerifyTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxRequest.ProtoReflect.Descriptor instead.
func (*VerifyTxRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTxRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *VerifyTxRequest) GetExpectedReceiver() string {
	if x != nil {
		return x.ExpectedReceiver
	}
	return ""
}

func (x *VerifyTxRequest) GetExpectedAmount() float64 {
	if x != nil {
		return x.ExpectedAmount
	}
	return 0
}

type VerifyTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	SenderAddress string                 `protobuf:"bytes,3,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTxResponse) Reset() {
	*x = VerifyTxResponse{}
	mi := &file_sovereign_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxResponse) ProtoMessage() {}

func (x *VerifyTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxResponse.ProtoReflect.Descriptor instead.
func (*VerifyTxResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTxResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyTxResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *VerifyTxResponse) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

type PaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientId    string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	AmountPi       float64                `protobuf:"fixed64,2,opt,name=amount_pi,json=amountPi,proto3" json:"amount_pi,omitempty"`
	AgentAuthToken string                 `protobuf:"bytes,3,opt,name=agent_auth_token,json=agentAuthToken,proto3" json:"agent_auth_token,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_sovereign_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *PaymentRequest) GetAmountPi() float64 {
	if x != nil {
		return x.AmountPi
	}
	return 0
}

func (x *PaymentRequest) GetAgentAuthToken() string {
	if x != nil {
		return x.AgentAuthToken
	}
	return ""
}

func (x *PaymentRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxId          string                 `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ExplorerUrl   string                 `protobuf:"bytes,3,opt,name=explorer_url,json=explorerUrl,proto3" json:"explorer_url,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_sovereign_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PaymentResponse) GetExplorerUrl() string {
	if x != nil {
		return x.ExplorerUrl
	}
	return ""
}

func (x *PaymentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PluginRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PluginId            string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	SourceCode          string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	EnvVars             map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowedCapabilities []string               `protobuf:"bytes,4,rep,name=allowed_capabilities,json=allowedCapabilities,proto3" json:"allowed_capabilities,omitempty"`
	Signature           string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginRequest) Reset() {
	*x = PluginRequest{}
	mi := &file_sovereign_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRequest) ProtoMessage() {}

func (x *PluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRequest.ProtoReflect.Descriptor instead.
func (*PluginRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{11}
}

func (x *PluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *PluginRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *PluginRequest) GetAllowedCapabilities() []string {
	if x != nil {
		return x.AllowedCapabilities
	}
	return nil
}

func (x *PluginRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type PluginResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PluginId        string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	OutputJson      string                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Logs            []string               `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginResponse) Reset() {
	*x = PluginResponse{}
	mi := &file_sovereign_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResponse) ProtoMessage() {}

func (x *PluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResponse.ProtoReflect.Descriptor instead.
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{12}
}

func (x *PluginResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *PluginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PluginResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *PluginResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type MemoryInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Relevance     float32                `protobuf:"fixed32,7,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInsight) Reset() {
	*x = MemoryInsight{}
	mi := &file_sovereign_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInsight) ProtoMessage() {}

func (x *MemoryInsight) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInsight.ProtoReflect.Descriptor instead.
func (*MemoryInsight) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{13}
}

func (x *MemoryInsight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryInsight) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryInsight) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MemoryInsight) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *MemoryInsight) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MemoryInsight) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MemoryInsight) GetRelevance() float32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

type MemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MemoryId      string                 `protobuf:"bytes,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResponse) Reset() {
	*x = MemoryResponse{}
	mi := &file_sovereign_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResponse) ProtoMessage() {}

func (x *MemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResponse.ProtoReflect.Descriptor instead.
func (*MemoryResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{14}
}

func (x *MemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MemoryResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type MemoryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SemanticQuery string                 `protobuf:"bytes,3,opt,name=semantic_query,json=semanticQuery,proto3" json:"semantic_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryQuery) Reset() {
	*x = MemoryQuery{}
	mi := &file_sovereign_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryQuery) ProtoMessage() {}

func (x *MemoryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryQuery.ProtoReflect.Descriptor instead.
func (*MemoryQuery) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{15}
}

func (x *MemoryQuery) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MemoryQuery) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryQuery) GetSemanticQuery() string {
	if x != nil {
		return x.SemanticQuery
	}
	return ""
}

type SubWalletRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MasterSeedCipher []byte                 `protobuf:"bytes,2,opt,name=master_seed_cipher,json=masterSeedCipher,proto3" json:"master_seed_cipher,omitempty"` // AES-256-GCM encrypted master seed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubWalletRequest) Reset() {
	*x = SubWalletRequest{}
	mi := &file_sovereign_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubWalletRequest) ProtoMessage() {}

func (x *SubWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubWalletRequest.ProtoReflect.Descriptor instead.
func (*SubWalletRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{16}
}

func (x *SubWalletRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubWalletRequest) GetMasterSeedCipher() []byte {
	if x != nil {
		return x.MasterSeedCipher
	}
	return nil
}

type SubWalletResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SubWalletAddress string                 `protobuf:"bytes,2,opt,name=sub_wallet_address,json=subWalletAddress,proto3" json:"sub_wallet_address,omitempty"`
	PublicKeyHex     string                 `protobuf:"bytes,3,opt,name=public_key_hex,json=publicKeyHex,proto3" json:"public_key_hex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubWalletResponse) Reset() {
	*x = SubWalletResponse{}
	mi := &file_sovereign_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubWalletResponse) ProtoMessage() {}

func (x *SubWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubWalletResponse.ProtoReflect.Descriptor instead.
func (*SubWalletResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{17}
}

func (x *SubWalletResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubWalletResponse) GetSubWalletAddress() string {
	if x != nil {
		return x.SubWalletAddress
	}
	return ""
}

func (x *SubWalletResponse) GetPublicKeyHex() string {
	if x != nil {
		return x.PublicKeyHex
	}
	return ""
}

type AgentPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,1,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // Can be another agent or a service address
	AmountPi      float64                `protobuf:"fixed64,3,opt,name=amount_pi,json=amountPi,proto3" json:"amount_pi,omitempty"`
	Memo          string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // Signed by agent's session key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPaymentRequest) Reset() {
	*x = AgentPaymentRequest{}
	mi := &file_sovereign_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPaymentRequest) ProtoMessage() {}

func (x *AgentPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPaymentRequest.ProtoReflect.Descriptor instead.
func (*AgentPaymentRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{18}
}

func (x *AgentPaymentRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *AgentPaymentRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AgentPaymentRequest) GetAmountPi() float64 {
	if x != nil {
		return x.AmountPi
	}
	return 0
}

func (x *AgentPaymentRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *AgentPaymentRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AgentPaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash           string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RemainingBalance float64                `protobuf:"fixed64,4,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentPaymentResponse) Reset() {
	*x = AgentPaymentResponse{}
	mi := &file_sovereign_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPaymentResponse) ProtoMessage() {}

func (x *AgentPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPaymentResponse.ProtoReflect.Descriptor instead.
func (*AgentPaymentResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{19}
}

func (x *AgentPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentPaymentResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AgentPaymentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AgentPaymentResponse) GetRemainingBalance() float64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

type MemoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insights      []*MemoryInsight       `protobuf:"bytes,1,rep,name=insights,proto3" json:"insights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryList) Reset() {
	*x = MemoryList{}
	mi := &file_sovereign_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryList) ProtoMessage() {}

func (x *MemoryList) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryList.ProtoReflect.Descriptor instead.
func (*MemoryList) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{20}
}

func (x *MemoryList) GetInsights() []*MemoryInsight {
	if x != nil {
		return x.Insights
	}
	return nil
}

type KYARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OwnerPiId     string                 `protobuf:"bytes,2,opt,name=owner_pi_id,json=ownerPiId,proto3" json:"owner_pi_id,omitempty"`
	KycProofToken string                 `protobuf:"bytes,3,opt,name=kyc_proof_token,json=kycProofToken,proto3" json:"kyc_proof_token,omitempty"` // From Pi KYC service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KYARequest) Reset() {
	*x = KYARequest{}
	mi := &file_sovereign_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYARequest) ProtoMessage() {}

func (x *KYARequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYARequest.ProtoReflect.Descriptor instead.
func (*KYARequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{21}
}

func (x *KYARequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KYARequest) GetOwnerPiId() string {
	if x != nil {
		return x.OwnerPiId
	}
	return ""
}

func (x *KYARequest) GetKycProofToken() string {
	if x != nil {
		return x.KycProofToken
	}
	return ""
}

type AIXPassport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OwnerPiId     string                 `protobuf:"bytes,2,opt,name=owner_pi_id,json=ownerPiId,proto3" json:"owner_pi_id,omitempty"`
	IssuanceDate  string                 `protobuf:"bytes,3,opt,name=issuance_date,json=issuanceDate,proto3" json:"issuance_date,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	KycStatus     string                 `protobuf:"bytes,5,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	ZkpCommitment string                 `protobuf:"bytes,6,opt,name=zkp_commitment,json=zkpCommitment,proto3" json:"zkp_commitment,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"` // Sovereign Engine Signature
	Attributes    map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIXPassport) Reset() {
	*x = AIXPassport{}
	mi := &file_sovereign_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIXPassport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIXPassport) ProtoMessage() {}

func (x *AIXPassport) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIXPassport.ProtoReflect.Descriptor instead.
func (*AIXPassport) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{22}
}

func (x *AIXPassport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AIXPassport) GetOwnerPiId() string {
	if x != nil {
		return x.OwnerPiId
	}
	return ""
}

func (x *AIXPassport) GetIssuanceDate() string {
	if x != nil {
		return x.IssuanceDate
	}
	return ""
}

func (x *AIXPassport) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *AIXPassport) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *AIXPassport) GetZkpCommitment() string {
	if x != nil {
		return x.ZkpCommitment
	}
	return ""
}

func (x *AIXPassport) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AIXPassport) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type VerifyKYARequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Passport       *AIXPassport           `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	Challenge      string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	AgentSignature string                 `protobuf:"bytes,3,opt,name=agent_signature,json=agentSignature,proto3" json:"agent_signature,omitempty"` // Signature of the challenge by the agent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyKYARequest) Reset() {
	*x = VerifyKYARequest{}
	mi := &file_sovereign_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyKYARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyKYARequest) ProtoMessage() {}

func (x *VerifyKYARequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyKYARequest.ProtoReflect.Descriptor instead.
func (*VerifyKYARequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{23}
}

func (x *VerifyKYARequest) GetPassport() *AIXPassport {
	if x != nil {
		return x.Passport
	}
	return nil
}

func (x *VerifyKYARequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *VerifyKYARequest) GetAgentSignature() string {
	if x != nil {
		return x.AgentSignature
	}
	return ""
}

type VerifyKYAResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Valid                  bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	VerificationMessage    string                 `protobuf:"bytes,2,opt,name=verification_message,json=verificationMessage,proto3" json:"verification_message,omitempty"`
	OwnerVerificationLevel string                 `protobuf:"bytes,3,opt,name=owner_verification_level,json=ownerVerificationLevel,proto3" json:"owner_verification_level,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VerifyKYAResponse) Reset() {
	*x = VerifyKYAResponse{}
	mi := &file_sovereign_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyKYAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyKYAResponse) ProtoMessage() {}

func (x *VerifyKYAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyKYAResponse.ProtoReflect.Descriptor instead.
func (*VerifyKYAResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{24}
}

func (x *VerifyKYAResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyKYAResponse) GetVerificationMessage() string {
	if x != nil {
		return x.VerificationMessage
	}
	return ""
}

func (x *VerifyKYAResponse) GetOwnerVerificationLevel() string {
	if x != nil {
		return x.OwnerVerificationLevel
	}
	return ""
}

type IntentBountyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CreatorId         string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	IntentDescription string                 `protobuf:"bytes,2,opt,name=intent_description,json=intentDescription,proto3" json:"intent_description,omitempty"`
	AmountPi          float64                `protobuf:"fixed64,3,opt,name=amount_pi,json=amountPi,proto3" json:"amount_pi,omitempty"`
	Expiry            string                 `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Constraints       map[string]string      `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntentBountyRequest) Reset() {
	*x = IntentBountyRequest{}
	mi := &file_sovereign_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentBountyRequest) ProtoMessage() {}

func (x *IntentBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentBountyRequest.ProtoReflect.Descriptor instead.
func (*IntentBountyRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{25}
}

func (x *IntentBountyRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *IntentBountyRequest) GetIntentDescription() string {
	if x != nil {
		return x.IntentDescription
	}
	return ""
}

func (x *IntentBountyRequest) GetAmountPi() float64 {
	if x != nil {
		return x.AmountPi
	}
	return 0
}

func (x *IntentBountyRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *IntentBountyRequest) GetConstraints() map[string]string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type IntentBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      string                 `protobuf:"bytes,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	EscrowAddress string                 `protobuf:"bytes,2,opt,name=escrow_address,json=escrowAddress,proto3" json:"escrow_address,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentBountyResponse) Reset() {
	*x = IntentBountyResponse{}
	mi := &file_sovereign_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentBountyResponse) ProtoMessage() {}

func (x *IntentBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentBountyResponse.ProtoReflect.Descriptor instead.
func (*IntentBountyResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{26}
}

func (x *IntentBountyResponse) GetBountyId() string {
	if x != nil {
		return x.BountyId
	}
	return ""
}

func (x *IntentBountyResponse) GetEscrowAddress() string {
	if x != nil {
		return x.EscrowAddress
	}
	return ""
}

func (x *IntentBountyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResolveBountyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BountyId        string                 `protobuf:"bytes,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	SolverId        string                 `protobuf:"bytes,2,opt,name=solver_id,json=solverId,proto3" json:"solver_id,omitempty"`
	ProofData       string                 `protobuf:"bytes,3,opt,name=proof_data,json=proofData,proto3" json:"proof_data,omitempty"`
	SolverSignature string                 `protobuf:"bytes,4,opt,name=solver_signature,json=solverSignature,proto3" json:"solver_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveBountyRequest) Reset() {
	*x = ResolveBountyRequest{}
	mi := &file_sovereign_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBountyRequest) ProtoMessage() {}

func (x *ResolveBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBountyRequest.ProtoReflect.Descriptor instead.
func (*ResolveBountyRequest) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{27}
}

func (x *ResolveBountyRequest) GetBountyId() string {
	if x != nil {
		return x.BountyId
	}
	return ""
}

func (x *ResolveBountyRequest) GetSolverId() string {
	if x != nil {
		return x.SolverId
	}
	return ""
}

func (x *ResolveBountyRequest) GetProofData() string {
	if x != nil {
		return x.ProofData
	}
	return ""
}

func (x *ResolveBountyRequest) GetSolverSignature() string {
	if x != nil {
		return x.SolverSignature
	}
	return ""
}

type ResolveBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBountyResponse) Reset() {
	*x = ResolveBountyResponse{}
	mi := &file_sovereign_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBountyResponse) ProtoMessage() {}

func (x *ResolveBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBountyResponse.ProtoReflect.Descriptor instead.
func (*ResolveBountyResponse) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{28}
}

func (x *ResolveBountyResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ResolveBountyResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ResolveBountyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BountyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BountyQuery) Reset() {
	*x = BountyQuery{}
	mi := &file_sovereign_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyQuery) ProtoMessage() {}

func (x *BountyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyQuery.ProtoReflect.Descriptor instead.
func (*BountyQuery) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{29}
}

func (x *BountyQuery) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *BountyQuery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BountyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounties      []*IntentBounty        `protobuf:"bytes,1,rep,name=bounties,proto3" json:"bounties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BountyList) Reset() {
	*x = BountyList{}
	mi := &file_sovereign_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyList) ProtoMessage() {}

func (x *BountyList) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyList.ProtoReflect.Descriptor instead.
func (*BountyList) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{30}
}

func (x *BountyList) GetBounties() []*IntentBounty {
	if x != nil {
		return x.Bounties
	}
	return nil
}

type IntentBounty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      string                 `protobuf:"bytes,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AmountPi      float64                `protobuf:"fixed64,4,opt,name=amount_pi,json=amountPi,proto3" json:"amount_pi,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentBounty) Reset() {
	*x = IntentBounty{}
	mi := &file_sovereign_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentBounty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentBounty) ProtoMessage() {}

func (x *IntentBounty) ProtoReflect() protoreflect.Message {
	mi := &file_sovereign_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentBounty.ProtoReflect.Descriptor instead.
func (*IntentBounty) Descriptor() ([]byte, []int) {
	return file_sovereign_proto_rawDescGZIP(), []int{31}
}

func (x *IntentBounty) GetBountyId() string {
	if x != nil {
		return x.BountyId
	}
	return ""
}

func (x *IntentBounty) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *IntentBounty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntentBounty) GetAmountPi() float64 {
	if x != nil {
		return x.AmountPi
	}
	return 0
}

func (x *IntentBounty) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_sovereign_proto protoreflect.FileDescriptor

const file_sovereign_proto_rawDesc = "" +
	"\n" +
	"\x0fsovereign.proto\x12\tsovereign\"\xab\x01\n" +
	"\x11SimulationRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12\x1c\n" +
	"\tinstances\x18\x02 \x01(\x05R\tinstances\x12\x1e\n" +
	"\n" +
	"complexity\x18\x03 \x01(\x02R\n" +
	"complexity\x12\x1a\n" +
	"\bpersonas\x18\x04 \x03(\tR\bpersonas\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\"\x98\x02\n" +
	"\x12SimulationResponse\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\tR\x06goalId\x12#\n" +
	"\rpredicted_roi\x18\x02 \x01(\x02R\fpredictedRoi\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\x127\n" +
	"\x17strategy_recommendation\x18\x04 \x01(\tR\x16strategyRecommendation\x128\n" +
	"\treasoning\x18\x05 \x01(\v2\x1a.sovereign.GeminiReasoningR\treasoning\x122\n" +
	"\x15estimated_revenue_usd\x18\x06 \x01(\x02R\x13estimatedRevenueUsd\"\xaa\x01\n" +
	"\x0fGeminiReasoning\x12\x1f\n" +
	"\vlogic_chain\x18\x01 \x01(\tR\n" +
	"logicChain\x12%\n" +
	"\x0ecritical_risks\x18\x02 \x03(\tR\rcriticalRisks\x12$\n" +
	"\ropportunities\x18\x03 \x03(\tR\ropportunities\x12)\n" +
	"\x10confidence_score\x18\x04 \x01(\tR\x0fconfidenceScore\"\x94\x03\n" +
	"\x0eEmbodiedIntent\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12)\n" +
	"\x10subtask_language\x18\x03 \x01(\tR\x0fsubtaskLanguage\x12_\n" +
	"\x12execution_metadata\x18\x04 \x03(\v20.sovereign.EmbodiedIntent.ExecutionMetadataEntryR\x11executionMetadata\x12!\n" +
	"\fcontrol_mode\x18\x05 \x01(\tR\vcontrolMode\x12'\n" +
	"\x0fvisual_subgoals\x18\x06 \x03(\fR\x0evisualSubgoals\x12\x12\n" +
	"\x04goal\x18\a \x01(\tR\x04goal\x12\x18\n" +
	"\apersona\x18\b \x01(\tR\apersona\x1aD\n" +
	"\x16ExecutionMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x0eIntentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vtracking_id\x18\x03 \x01(\tR\n" +
	"trackingId\"f\n" +
	"\rEscrowRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x1b\n" +
	"\tamount_pi\x18\x02 \x01(\x01R\bamountPi\x12#\n" +
	"\rtarget_wallet\x18\x03 \x01(\tR\ftargetWallet\"O\n" +
	"\x0eEscrowResponse\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\x12%\n" +
	"\x0eescrow_address\x18\x02 \x01(\tR\rescrowAddress\"|\n" +
	"\x0fVerifyTxRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12+\n" +
	"\x11expected_receiver\x18\x02 \x01(\tR\x10expectedReceiver\x12'\n" +
	"\x0fexpected_amount\x18\x03 \x01(\x01R\x0eexpectedAmount\"|\n" +
	"\x10VerifyTxResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12%\n" +
	"\x0esender_address\x18\x03 \x01(\tR\rsenderAddress\"\x96\x01\n" +
	"\x0ePaymentRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x1b\n" +
	"\tamount_pi\x18\x02 \x01(\x01R\bamountPi\x12(\n" +
	"\x10agent_auth_token\x18\x03 \x01(\tR\x0eagentAuthToken\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\"\x88\x01\n" +
	"\x0fPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\x12!\n" +
	"\fexplorer_url\x18\x03 \x01(\tR\vexplorerUrl\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x9c\x02\n" +
	"\rPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x12@\n" +
	"\benv_vars\x18\x03 \x03(\v2%.sovereign.PluginRequest.EnvVarsEntryR\aenvVars\x121\n" +
	"\x14allowed_capabilities\x18\x04 \x03(\tR\x13allowedCapabilities\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x0ePluginResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\x12\x12\n" +
	"\x04logs\x18\x06 \x03(\tR\x04logs\"\xc7\x01\n" +
	"\rMemoryInsight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\trelevance\x18\a \x01(\x02R\trelevance\"G\n" +
	"\x0eMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tmemory_id\x18\x02 \x01(\tR\bmemoryId\"e\n" +
	"\vMemoryQuery\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12%\n" +
	"\x0esemantic_query\x18\x03 \x01(\tR\rsemanticQuery\"[\n" +
	"\x10SubWalletRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x12master_seed_cipher\x18\x02 \x01(\fR\x10masterSeedCipher\"\x82\x01\n" +
	"\x11SubWalletResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x12sub_wallet_address\x18\x02 \x01(\tR\x10subWalletAddress\x12$\n" +
	"\x0epublic_key_hex\x18\x03 \x01(\tR\fpublicKeyHex\"\xa9\x01\n" +
	"\x13AgentPaymentRequest\x12&\n" +
	"\x0fsource_agent_id\x18\x01 \x01(\tR\rsourceAgentId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1b\n" +
	"\tamount_pi\x18\x03 \x01(\x01R\bamountPi\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"\x9b\x01\n" +
	"\x14AgentPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11remaining_balance\x18\x04 \x01(\x01R\x10remainingBalance\"B\n" +
	"\n" +
	"MemoryList\x124\n" +
	"\binsights\x18\x01 \x03(\v2\x18.sovereign.MemoryInsightR\binsights\"o\n" +
	"\n" +
	"KYARequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1e\n" +
	"\vowner_pi_id\x18\x02 \x01(\tR\townerPiId\x12&\n" +
	"\x0fkyc_proof_token\x18\x03 \x01(\tR\rkycProofToken\"\xf9\x02\n" +
	"\vAIXPassport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1e\n" +
	"\vowner_pi_id\x18\x02 \x01(\tR\townerPiId\x12#\n" +
	"\rissuance_date\x18\x03 \x01(\tR\fissuanceDate\x12\x1f\n" +
	"\vexpiry_date\x18\x04 \x01(\tR\n" +
	"expiryDate\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x05 \x01(\tR\tkycStatus\x12%\n" +
	"\x0ezkp_commitment\x18\x06 \x01(\tR\rzkpCommitment\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12F\n" +
	"\n" +
	"attributes\x18\b \x03(\v2&.sovereign.AIXPassport.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x10VerifyKYARequest\x122\n" +
	"\bpassport\x18\x01 \x01(\v2\x16.sovereign.AIXPassportR\bpassport\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12'\n" +
	"\x0fagent_signature\x18\x03 \x01(\tR\x0eagentSignature\"\x96\x01\n" +
	"\x11VerifyKYAResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x121\n" +
	"\x14verification_message\x18\x02 \x01(\tR\x13verificationMessage\x128\n" +
	"\x18owner_verification_level\x18\x03 \x01(\tR\x16ownerVerificationLevel\"\xab\x02\n" +
	"\x13IntentBountyRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12-\n" +
	"\x12intent_description\x18\x02 \x01(\tR\x11intentDescription\x12\x1b\n" +
	"\tamount_pi\x18\x03 \x01(\x01R\bamountPi\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12Q\n" +
	"\vconstraints\x18\x05 \x03(\v2/.sovereign.IntentBountyRequest.ConstraintsEntryR\vconstraints\x1a>\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x14IntentBountyResponse\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\tR\bbountyId\x12%\n" +
	"\x0eescrow_address\x18\x02 \x01(\tR\rescrowAddress\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x14ResolveBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\tR\bbountyId\x12\x1b\n" +
	"\tsolver_id\x18\x02 \x01(\tR\bsolverId\x12\x1d\n" +
	"\n" +
	"proof_data\x18\x03 \x01(\tR\tproofData\x12)\n" +
	"\x10solver_signature\x18\x04 \x01(\tR\x0fsolverSignature\"d\n" +
	"\x15ResolveBountyResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"D\n" +
	"\vBountyQuery\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"A\n" +
	"\n" +
	"BountyList\x123\n" +
	"\bbounties\x18\x01 \x03(\v2\x17.sovereign.IntentBountyR\bbounties\"\xa1\x01\n" +
	"\fIntentBounty\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\tR\bbountyId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tamount_pi\x18\x04 \x01(\x01R\bamountPi\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\x87\t\n" +
	"\x10SovereignService\x12P\n" +
	"\x11RequestSimulation\x12\x1c.sovereign.SimulationRequest\x1a\x1d.sovereign.SimulationResponse\x12A\n" +
	"\n" +
	"LockEscrow\x12\x18.sovereign.EscrowRequest\x1a\x19.sovereign.EscrowResponse\x12L\n" +
	"\x11VerifyTransaction\x12\x1a.sovereign.VerifyTxRequest\x1a\x1b.sovereign.VerifyTxResponse\x12F\n" +
	"\rCommitPayment\x12\x19.sovereign.PaymentRequest\x1a\x1a.sovereign.PaymentResponse\x12J\n" +
	"\x12SendEmbodiedIntent\x12\x19.sovereign.EmbodiedIntent\x1a\x19.sovereign.IntentResponse\x12D\n" +
	"\rExecutePlugin\x12\x18.sovereign.PluginRequest\x1a\x19.sovereign.PluginResponse\x12B\n" +
	"\vStoreMemory\x12\x18.sovereign.MemoryInsight\x1a\x19.sovereign.MemoryResponse\x12<\n" +
	"\vQueryMemory\x12\x16.sovereign.MemoryQuery\x1a\x15.sovereign.MemoryList\x12T\n" +
	"\x17AuthorizeAgentSubWallet\x12\x1b.sovereign.SubWalletRequest\x1a\x1c.sovereign.SubWalletResponse\x12V\n" +
	"\x13ProcessAgentPayment\x12\x1e.sovereign.AgentPaymentRequest\x1a\x1f.sovereign.AgentPaymentResponse\x12A\n" +
	"\x10IssueAIXPassport\x12\x15.sovereign.KYARequest\x1a\x16.sovereign.AIXPassport\x12N\n" +
	"\x11VerifyAIXPassport\x12\x1b.sovereign.VerifyKYARequest\x1a\x1c.sovereign.VerifyKYAResponse\x12U\n" +
	"\x12CreateIntentBounty\x12\x1e.sovereign.IntentBountyRequest\x1a\x1f.sovereign.IntentBountyResponse\x12X\n" +
	"\x13ResolveIntentBounty\x12\x1f.sovereign.ResolveBountyRequest\x1a .sovereign.ResolveBountyResponse\x12B\n" +
	"\x11GetActiveBounties\x12\x16.sovereign.BountyQuery\x1a\x15.sovereign.BountyListB\x0fZ\r./internal/pbb\x06proto3"

var (
	file_sovereign_proto_rawDescOnce sync.Once
	file_sovereign_proto_rawDescData []byte
)

func file_sovereign_proto_rawDescGZIP() []byte {
	file_sovereign_proto_rawDescOnce.Do(func() {
		file_sovereign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sovereign_proto_rawDesc), len(file_sovereign_proto_rawDesc)))
	})
	return file_sovereign_proto_rawDescData
}

var file_sovereign_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_sovereign_proto_goTypes = []any{
	(*SimulationRequest)(nil),     // 0: sovereign.SimulationRequest
	(*SimulationResponse)(nil),    // 1: sovereign.SimulationResponse
	(*GeminiReasoning)(nil),       // 2: sovereign.GeminiReasoning
	(*EmbodiedIntent)(nil),        // 3: sovereign.EmbodiedIntent
	(*IntentResponse)(nil),        // 4: sovereign.IntentResponse
	(*EscrowRequest)(nil),         // 5: sovereign.EscrowRequest
	(*EscrowResponse)(nil),        // 6: sovereign.EscrowResponse
	(*VerifyTxRequest)(nil),       // 7: sovereign.VerifyTxRequest
	(*VerifyTxResponse)(nil),      // 8: sovereign.VerifyTxResponse
	(*PaymentRequest)(nil),        // 9: sovereign.PaymentRequest
	(*PaymentResponse)(nil),       // 10: sovereign.PaymentResponse
	(*PluginRequest)(nil),         // 11: sovereign.PluginRequest
	(*PluginResponse)(nil),        // 12: sovereign.PluginResponse
	(*MemoryInsight)(nil),         // 13: sovereign.MemoryInsight
	(*MemoryResponse)(nil),        // 14: sovereign.MemoryResponse
	(*MemoryQuery)(nil),           // 15: sovereign.MemoryQuery
	(*SubWalletRequest)(nil),      // 16: sovereign.SubWalletRequest
	(*SubWalletResponse)(nil),     // 17: sovereign.SubWalletResponse
	(*AgentPaymentRequest)(nil),   // 18: sovereign.AgentPaymentRequest
	(*AgentPaymentResponse)(nil),  // 19: sovereign.AgentPaymentResponse
	(*MemoryList)(nil),            // 20: sovereign.MemoryList
	(*KYARequest)(nil),            // 21: sovereign.KYARequest
	(*AIXPassport)(nil),           // 22: sovereign.AIXPassport
	(*VerifyKYARequest)(nil),      // 23: sovereign.VerifyKYARequest
	(*VerifyKYAResponse)(nil),     // 24: sovereign.VerifyKYAResponse
	(*IntentBountyRequest)(nil),   // 25: sovereign.IntentBountyRequest
	(*IntentBountyResponse)(nil),  // 26: sovereign.IntentBountyResponse
	(*ResolveBountyRequest)(nil),  // 27: sovereign.ResolveBountyRequest
	(*ResolveBountyResponse)(nil), // 28: sovereign.ResolveBountyResponse
	(*BountyQuery)(nil),           // 29: sovereign.BountyQuery
	(*BountyList)(nil),            // 30: sovereign.BountyList
	(*IntentBounty)(nil),          // 31: sovereign.IntentBounty
	nil,                           // 32: sovereign.EmbodiedIntent.ExecutionMetadataEntry
	nil,                           // 33: sovereign.PluginRequest.EnvVarsEntry
	nil,                           // 34: sovereign.AIXPassport.AttributesEntry
	nil,                           // 35: sovereign.IntentBountyRequest.ConstraintsEntry
}
var file_sovereign_proto_depIdxs = []int32{
	2,  // 0: sovereign.SimulationResponse.reasoning:type_name -> sovereign.GeminiReasoning
	32, // 1: sovereign.EmbodiedIntent.execution_metadata:type_name -> sovereign.EmbodiedIntent.ExecutionMetadataEntry
	33, // 2: sovereign.PluginRequest.env_vars:type_name -> sovereign.PluginRequest.EnvVarsEntry
	13, // 3: sovereign.MemoryList.insights:type_name -> sovereign.MemoryInsight
	34, // 4: sovereign.AIXPassport.attributes:type_name -> sovereign.AIXPassport.AttributesEntry
	22, // 5: sovereign.VerifyKYARequest.passport:type_name -> sovereign.AIXPassport
	35, // 6: sovereign.IntentBountyRequest.constraints:type_name -> sovereign.IntentBountyRequest.ConstraintsEntry
	31, // 7: sovereign.BountyList.bounties:type_name -> sovereign.IntentBounty
	0,  // 8: sovereign.SovereignService.RequestSimulation:input_type -> sovereign.SimulationRequest
	5,  // 9: sovereign.SovereignService.LockEscrow:input_type -> sovereign.EscrowRequest
	7,  // 10: sovereign.SovereignService.VerifyTransaction:input_type -> sovereign.VerifyTxRequest
	9,  // 11: sovereign.SovereignService.CommitPayment:input_type -> sovereign.PaymentRequest
	3,  // 12: sovereign.SovereignService.SendEmbodiedIntent:input_type -> sovereign.EmbodiedIntent
	11, // 13: sovereign.SovereignService.ExecutePlugin:input_type -> sovereign.PluginRequest
	13, // 14: sovereign.SovereignService.StoreMemory:input_type -> sovereign.MemoryInsight
	15, // 15: sovereign.SovereignService.QueryMemory:input_type -> sovereign.MemoryQuery
	16, // 16: sovereign.SovereignService.AuthorizeAgentSubWallet:input_type -> sovereign.SubWalletRequest
	18, // 17: sovereign.SovereignService.ProcessAgentPayment:input_type -> sovereign.AgentPaymentRequest
	21, // 18: sovereign.SovereignService.IssueAIXPassport:input_type -> sovereign.KYARequest
	23, // 19: sovereign.SovereignService.VerifyAIXPassport:input_type -> sovereign.VerifyKYARequest
	25, // 20: sovereign.SovereignService.CreateIntentBounty:input_type -> sovereign.IntentBountyRequest
	27, // 21: sovereign.SovereignService.ResolveIntentBounty:input_type -> sovereign.ResolveBountyRequest
	29, // 22: sovereign.SovereignService.GetActiveBounties:input_type -> sovereign.BountyQuery
	1,  // 23: sovereign.SovereignService.RequestSimulation:output_type -> sovereign.SimulationResponse
	6,  // 24: sovereign.SovereignService.LockEscrow:output_type -> sovereign.EscrowResponse
	8,  // 25: sovereign.SovereignService.VerifyTransaction:output_type -> sovereign.VerifyTxResponse
	10, // 26: sovereign.SovereignService.CommitPayment:output_type -> sovereign.PaymentResponse
	4,  // 27: sovereign.SovereignService.SendEmbodiedIntent:output_type -> sovereign.IntentResponse
	12, // 28: sovereign.SovereignService.ExecutePlugin:output_type -> sovereign.PluginResponse
	14, // 29: sovereign.SovereignService.StoreMemory:output_type -> sovereign.MemoryResponse
	20, // 30: sovereign.SovereignService.QueryMemory:output_type -> sovereign.MemoryList
	17, // 31: sovereign.SovereignService.AuthorizeAgentSubWallet:output_type -> sovereign.SubWalletResponse
	19, // 32: sovereign.SovereignService.ProcessAgentPayment:output_type -> sovereign.AgentPaymentResponse
	22, // 33: sovereign.SovereignService.IssueAIXPassport:output_type -> sovereign.AIXPassport
	24, // 34: sovereign.SovereignService.VerifyAIXPassport:output_type -> sovereign.VerifyKYAResponse
	26, // 35: sovereign.SovereignService.CreateIntentBounty:output_type -> sovereign.IntentBountyResponse
	28, // 36: sovereign.SovereignService.ResolveIntentBounty:output_type -> sovereign.ResolveBountyResponse
	30, // 37: sovereign.SovereignService.GetActiveBounties:output_type -> sovereign.BountyList
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sovereign_proto_init() }
func file_sovereign_proto_init() {
	if File_sovereign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sovereign_proto_rawDesc), len(file_sovereign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sovereign_proto_goTypes,
		DependencyIndexes: file_sovereign_proto_depIdxs,
		MessageInfos:      file_sovereign_proto_msgTypes,
	}.Build()
	File_sovereign_proto = out.File
	file_sovereign_proto_goTypes = nil
	file_sovereign_proto_depIdxs = nil
}
