package bridge

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

// GeminiClient handles all interactions with Google's Generative AI.
// Following Best Practices: Encapsulation, Context support, and API Key safety.
type GeminiClient struct {
	client *genai.Client
	model  *genai.GenerativeModel
}

// NewGeminiClient initializes a new client with production-ready settings.
func NewGeminiClient(ctx context.Context, modelName string) (*GeminiClient, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("GEMINI_API_KEY not set in environment")
	}

	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return nil, fmt.Errorf("failed to create genai client: %w", err)
	}

	model := client.GenerativeModel(modelName)
	
	// Professional Tuning: Set safety settings and generation config
	model.SetTemperature(0.7)
	model.SetTopP(0.95)
	model.SetTopK(40)
	model.MaxOutputTokens = 2048

	return &GeminiClient{
		client: client,
		model:  model,
	}, nil
}

// Close ensures the client resources are released properly.
func (gc *GeminiClient) Close() {
	if gc.client != nil {
		gc.client.Close()
	}
}

// AnalyzeSimulationGoal uses Gemini to provide a deep reasoning chain for a specific goal.
func (gc *GeminiClient) AnalyzeSimulationGoal(ctx context.Context, goal string, persona string) (string, error) {
	prompt := fmt.Sprintf(`
		System: You are the Sovereign Reasoning Engine of PiWorker-OS.
		Context: Roleplay as a %s persona.
		Objective: Analyze the following goal and provide a logical execution chain.
		
		Goal: %s
		
		Output Format:
		1. REASONING: <your reasoning chain>
		2. RISKS: <identified risks>
		3. SUCCESS_PROBABILITY: <a single number between 0.0 and 1.0 representing the likelihood of achieving the goal>
	`, persona, goal)

	resp, err := gc.model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("gemini generation failed: %w", err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return "No reasoning generated by AI.", nil
	}

	// Extracting the text part from the response
	var reasoning string
	for _, part := range resp.Candidates[0].Content.Parts {
		reasoning += fmt.Sprintf("%v", part)
	}

	return reasoning, nil
}
