package bridge

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// OpenSourceClient handles interactions with OpenAI-compatible APIs (Gemma, DeepSeek, Mistral).
// This provides a cost-effective alternative using Google's Gemma models for routine tasks.
type OpenSourceClient struct {
	APIKey     string
	BaseURL    string
	ModelName  string
	HTTPClient *http.Client
}

type OpenAIRequest struct {
	Model    string          `json:"model"`
	Messages []OpenAIMessage `json:"messages"`
}

type OpenAIMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type OpenAIResponse struct {
	Choices []struct {
		Message OpenAIMessage `json:"message"`
	} `json:"choices"`
}

func NewOpenSourceClient(baseURL, apiKey, modelName string) *OpenSourceClient {
	if baseURL == "" {
		baseURL = "https://api.groq.com/openai/v1"
	}
	
	return &OpenSourceClient{
		APIKey:     apiKey,
		BaseURL:    baseURL,
		ModelName:  modelName,
		HTTPClient: &http.Client{},
	}
}

func (oc *OpenSourceClient) AnalyzeGoal(ctx context.Context, goal string, persona string) (string, error) {
	if oc.APIKey == "" {
		return "", fmt.Errorf("OPEN_SOURCE_API_KEY not set")
	}

	prompt := fmt.Sprintf("Goal: %s\nPersona: %s\nProvide a high-efficiency logical execution chain.", goal, persona)

	reqBody := OpenAIRequest{
		Model: oc.ModelName,
		Messages: []OpenAIMessage{
			{Role: "system", Content: "You are a highly efficient Sovereign Agentic Sub-Processor. Optimize for logical flow and cost-effectiveness."},
			{Role: "user", Content: prompt},
		},
	}

	jsonBody, _ := json.Marshal(reqBody)
	req, err := http.NewRequestWithContext(ctx, "POST", oc.BaseURL+"/chat/completions", bytes.NewBuffer(jsonBody))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+oc.APIKey)

	resp, err := oc.HTTPClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("API error (%d): %s", resp.StatusCode, string(body))
	}

	var openAIResp OpenAIResponse
	if err := json.NewDecoder(resp.Body).Decode(&openAIResp); err != nil {
		return "", err
	}

	if len(openAIResp.Choices) > 0 {
		return openAIResp.Choices[0].Message.Content, nil
	}

	return "No reasoning generated by Open Source model.", nil
}
